[![Binder](https://mybinder.org/badge_logo.svg)](https://nbviewer.org/github/Sistemas-Multimedia/Sistemas-Multimedia.github.io/blob/master/milestones/06-YUV_compression/color-DCT_matrix.ipynb)

# Color-DCT matrix computation
Inversely transform the posible deltas to get the 3x3 matrix coefficients.

In [1]:
import numpy as np
from scipy import signal
from scipy.fftpack import dct, idct

In [2]:
DCT_type = 3
norm = "ortho" # Orthonormal: orthogonal + unitary (unit gain in both directions of the transform)
#norm = None

In [3]:
DCT0_delta = np.array([1, 0, 0])
idct(DCT0_delta, type=DCT_type, norm=norm)

array([0.57735027, 0.70710678, 0.40824829])

In [4]:
DCT0_delta = np.array([0, 1, 0])
idct(DCT0_delta, type=DCT_type, norm=norm)

array([ 0.57735027,  0.        , -0.81649658])

In [5]:
DCT0_delta = np.array([0, 0, 1])
idct(DCT0_delta, type=DCT_type, norm=norm)

array([ 0.57735027, -0.70710678,  0.40824829])