[![Binder](https://mybinder.org/badge_logo.svg)](https://nbviewer.org/github/Sistemas-Multimedia/Sistemas-Multimedia.github.io/blob/master/milestones/06-YUV_compression/YCoCg_matrix.ipynb)

# YCoCg (inverse) matrix
Apply the YCoCg inverse transform to the deltas.

In [1]:
import numpy as np
import YCoCg

In [2]:
Y_delta = np.array([1, 0, 0]).reshape(1,1,3)
YCoCg.to_RGB(Y_delta)

array([[[1, 1, 1]]])

In [3]:
Cr_delta = np.array([0, 1, 0]).reshape(1,1,3)
YCoCg.to_RGB(Cr_delta)

array([[[ 1,  0, -1]]])

In [4]:
Cb_delta = np.array([0, 0, 1]).reshape(1,1,3)
YCoCg.to_RGB(Cb_delta)

array([[[-1,  1, -1]]])